### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by ENikS** [benchmarks/ioc-containers#2]
@danielpalme 

Daniel, this organization has been acquired to create 'centralized' place for all kind of benchmark projects. I was wandering if you would like to lead this one?

**Comment by danielpalme** [comment]
@ENikS 
Thanks for the invitation. 
I have created https://github.com/danielpalme/IocPerformance and invested a lot of time there.
Since my time is limited I will not start maintaining another benchmark.

**Comment by ENikS** [comment]
You could be owner of both of them. Consider it version 2. The offer still stands if you change your mind.

**Comment by danielpalme** [comment]
Thanks, but it is a time problem. At the moment, I'm too busy to start another project.
